export default {
  CONST_SYMBOL: 'CONST',
  STAKING_TYPES: {
    SHARD: 0,
    BEACON: 1
  },
  STAKING_AMOUNT: 200,
  STAKING_MIN_FEE: 0.01,
  STAKING_ADDRESS: '1NHp2EKw7ALdXUzBfoRJvKrBBM9nkejyDcHVPvUjDcWRyG22dHHyiBKQGL1c',
  DEFRAGMENT_DEFAULT_AMOUNT: 1,
  DEFRAGMENT_MIN_FEE: 0.01,
  DEFRAGMENT_SET_DEFAULT_PRIVACY: true,

  MILICONSTANT_UNIT: 100,
  AMOUNT_CONSTANT_MIN: 0.01,
  AMOUNT_TOKEN_MIN: 0.01,
  INIT_TOKEN: 0,
  SEND_TOKEN: 1,
  NORMAL_TOKEN_TAB: 0,
  PRIVACY_TOKEN_TAB: 1,
};